### ISSUE TITLE
TypeError: 'int' object is not subscriptable when attempting to load image file

### ISSUE THREAD

**Issue by madmodder123** [MircoT/pyTGA#2]
I am trying to use pyTGA to display a tga file directly to the framebuffer but I keep running into issues.

This is the error I get:
`Traceback (most recent call last):
  File "/home/pigaming/pyTGA-master/test.py", line 26, in <module>
    f.write(p[2].to_bytes(1, byteorder='little'))
TypeError: 'int' object is not subscriptable
`

The command:
`python3 test.py 1920 750 300 /home/pigaming/test.tga /dev/fb0`

The code:
```
import sys
import os
import pyTGA

if len(sys.argv) < 4:
  print("Usage: tga.py xsize xoff yoff input output")
  sys.exit(1)

g_xsize = int(sys.argv[1])
g_xoff = int(sys.argv[2])
g_yoff = int(sys.argv[3])
g_input = sys.argv[4]
g_output = sys.argv[5]

img = pyTGA.Image()
img.load(g_input)
header = img._header

with open(g_output, 'wb') as f:
  f.seek(g_yoff * 4 * g_xsize, os.SEEK_CUR)
  for y in range(header.image_height):
    f.seek(g_xoff * 4, os.SEEK_CUR)

    for x in range(header.image_width):
      p = img.get_pixel(y,x)
      f.write(p[2].to_bytes(1, byteorder='little'))
      f.write(p[1].to_bytes(1, byteorder='little'))
      f.write(p[0].to_bytes(1, byteorder='little'))
      f.write((0).to_bytes(1, byteorder='little'))

    f.seek((g_xsize - header.image_width - g_xoff) * 4, os.SEEK_CUR)
```
I got the code from here: http://seenaburns.com/2018/04/04/writing-to-the-framebuffer/
I noticed that the code had "import tga" instead of "import pyTGA" so I changed that (and the other tga entries)

**Comment by MircoT** [comment]
Check out the image type, because if you are using a BW image the function `get_pixel` will return only 1 integer number. Otherwise, if you have a normal RGB image in TGA, you will have a tuple of 3 elements like (int, int, int). Probably the error is caused by something like that.
