### ISSUE TITLE
struct.error: unpack requires a buffer of 1 bytes

### ISSUE THREAD

**Issue by Bra1nsen** [MircoT/pyTGA#4]
hej guys, thanks for sahring your work.

```
def exposure_bracket():
	
	picam2 = Picamera2()
	config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size": (2032, 1520)})
	picam2.configure(config)
	
	exposures = [50, 100, 150, 250, 400, 650, 1050, 1700, 2750]

	for exp in exposures:

		picam2.set_controls({"ExposureTime": exp, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
		picam2.start()
		time.sleep(0.5)
		array = picam2.capture_array("raw")
		picam2.stop()
		
		array16 = array.view(np.uint16)
		array16 *= 16  # Bump 12-bit range up to 16
		cv2.imwrite(f"{exp}_greyscale.png", array16)
		image = pyTGA.Image(data=array16)
		image.save(f"{exp}_greyscale")

		rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
		rgb_array[:, :, 0] = array16[1::2, 1::2] # red
		# Must avoid overflowing 16-bits in the addition here:
		rgb_array[:, :, 1] = (array16[0::2, 1::2].astype(int) + array16[1::2, 0::2]) / 2 # green
		rgb_array[:, :, 2] = array16[0::2, 0::2] # blue

		cv2.imwrite(f"{exp}_rgbraw.png", rgb_array)
		image = pyTGA.Image(data=rgb_array)
		image.save(f"{exp}_rgb")

			
exposure_bracket()

```

  **File "/home/pi/testrawbayer/pyTGA/tests/xxy.py", line 50, in <module>
    exposure_bracket()
  File "/home/pi/testrawbayer/pyTGA/tests/xxy.py", line 31, in exposure_bracket
    image.save(f"{exp}_greyscale")
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 739, in save
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 300, in __getitem__
struct.error: unpack requires a buffer of 1 bytes**

**Comment by Bra1nsen** [comment]
it does not support 16 bit greyscale or?

**Comment by Bra1nsen** [comment]
![Screenshot 2022-09-27 100059](https://user-images.githubusercontent.com/58213050/192468845-2e7e5865-6308-4c49-a6c1-6403164cc8dc.png)
![Screenshot 2022-09-27 100025](https://user-images.githubusercontent.com/58213050/192468850-a4e18d8c-95d6-4a1f-bf4e-67c84f07cdf7.png)

**Comment by MircoT** [comment]
> it does not support 16 bit greyscale or?

I don't understand the question. If the [image is type 3](https://en.wikipedia.org/wiki/Truevision_TGA) (`uncompressed black-and-white (grayscale) image`), it would have a 8 bit value for each pixel. You can't have a grayscale of 16 bit.

**Comment by Bra1nsen** [comment]
Hey Mirco sorry. I should have add [Enhancement] in the Titel.

I work with skycams for predicting solar power/ photovoltaic.

I would like to work with 16 bit Greyscale .TGA files. I'm not as skilled as you, how much effort would it be for you to add this feature? I would also pay you via PayPal if you're ok with that...
