### ISSUE TITLE
pyTGA.tga.ImageError: '[4096 4128 4144]' is not a valid pixel value

### ISSUE THREAD

**Issue by Bra1nsen** [MircoT/pyTGA#5]
I have a 16bit RGB Array with values between 0 and 4095..

why is it not possible to save as tga? Your Repo would be awesome if it would work :/

**Comment by MircoT** [comment]
Can you post an example to have some information about your problem?

**Comment by Bra1nsen** [comment]
Thanks for reply MircoT! =)

```
		picam2.set_controls({"ExposureTime": exp, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
		picam2.start()
		time.sleep(0.5)
		array = picam2.capture_array("raw")
		picam2.stop()
		#picam2.close()
		
		array16 = array.view(np.uint16)

		rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
		rgb_array[:, :, 0] = array16[1::2, 1::2] # red
		# Must avoid overflowing 16-bits in the addition here:
		rgb_array[:, :, 1] = (array16[0::2, 1::2].astype(int) + array16[1::2, 0::2]) / 2 # green
		rgb_array[:, :, 2] = array16[0::2, 0::2] # blue
		cv2.imwrite(f"{exp}_rgbraw.png", rgb_array)
		
		image = pyTGA.Image(data=rgb_array) #16Bit RGB
		image.save(f"{exp}_rgb", force_16_bit=True)

		# Load images back and check errors are zero!
		rgb_check = cv2.imread(f"{exp}_rgbraw.png", cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
		print(np.max(np.abs(rgb_array - rgb_check)))
```

```
Traceback (most recent call last):
  File "/home/pi/testrawbayer/pyTGA/tests/tgatest.py", line 47, in <module>
    exposure_bracket()
  File "/home/pi/testrawbayer/pyTGA/tests/tgatest.py", line 39, in exposure_bracket
    image = pyTGA.Image(data=rgb_array) #16Bit RGB
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 412, in __init__
  File "/usr/local/lib/python3.9/dist-packages/pyTGA-1.1.0-py3.9.egg/pyTGA/tga.py", line 477, in check
pyTGA.tga.ImageError: '[256 257 258]' is not a valid pixel value
```

**Comment by Bra1nsen** [comment]
<img width="749" alt="16bit" src="https://user-images.githubusercontent.com/58213050/193122489-813a1d9e-5246-41b0-b1fd-ea8299e121c6.png">

if I change one value beyond 255 the script errors.. What do you mean by 16 bit images?

**Comment by Bra1nsen** [comment]
MircoT can you please help me

**Comment by MircoT** [comment]
> array16 = array.view(np.uint16)

The problem is here. I see that you would manage an RGB image extracting the 3 color channels but, each color is a 8bit color. As a consequence, it will be a `uint8` array...

**Comment by Bra1nsen** [comment]
Do you work on upwork?
Do you currently have capacity for projects?
How much effort do you think it would be for you to extend the repo so that numpy arrays up to 32 bits per channel could be converted to .tga?

Kind regards
Paul

**Comment by MircoT** [comment]
> Do you work on upwork? Do you currently have capacity for projects? How much effort do you think it would be for you to extend the repo so that numpy arrays up to 32 bits per channel could be converted to .tga?
> 
> Kind regards Paul

The problem is that the source you are managing is wrong or something is missing. The stream [RGB has 3 dimensional array](https://picamera.readthedocs.io/en/release-1.13/api_array.html#pirgbarray). As a consequence, you could convert it directly to a TGA with the proper conversion but, TGA RGB are 24bit (8bit per color) and this is why the following code doesn't match:

```python
array16 = array.view(np.uint16)
```

As discussed, it is not a problem relative to this library or the TGA format, the problem is how you are capturing the input from the camera.

**Comment by Bra1nsen** [comment]
Mirco I would like to use .tga files with 16/32 bit per channel. I need a higher dynamic range. I understood that.

> > array16 = array.view(np.uint16)
> 
> The problem is here. I see that you would manage an RGB image extracting the 3 color channels but, each color is a 8bit color. As a consequence, it will be a `uint8` array...

Is there any chance to realize that?

**Comment by MircoT** [comment]
> Mirco I would like to use .tga files with 16/32 bit per channel. I need a higher dynamic range. I understood that.

It is not possible with the `.tga` format. You should consider managing that data differently.
